  name: pr-wk # you probably want to 'snapcraft register <name>'
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Sum the login session times from the last -F output # 79 char long summary
  description: |
    Script sums the login session times on a linux workstation. It prints the start/end
    dates for each week of the year for which there is login session data.
    Optionally the script prints the summary for one week using the week number.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil

